services:
  app:
    build: .
    ports:
      - "8002:8002"
    env_file: # Добавьте эту секцию
      - .env
    environment:
      - OPENAI_KEY=${OPENAI_KEY}

      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}

      - KAFKA_TOPIC_FOR_UPLOADING_DATA=${KAFKA_TOPIC_FOR_UPLOADING_DATA}
      - KAFKA_TOPIC_FOR_AI_HANDLER=${KAFKA_TOPIC_FOR_AI_HANDLER}
      - KAFKA_TOPIC_FOR_SENDING=${KAFKA_TOPIC_FOR_SENDING}

      - MODE=${MODE}
    depends_on:
      kafka:
        condition: service_started
    restart: unless-stopped  # Автоперезапуск при падении

  zookeeper:
    image: bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.6
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  postgres_data:  # Том для PostgreSQL
  redis_data:     # Том для Redis